swagger: "2.0"
info:
  description: "This is a sample swagger file for an ecommerce site with a small subset of APIs"
  version: "1.0.0"
  title: "E-commerce Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "nitin.k@srijan.net"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/v2"
tags:
- name: "ecom"
  description: "Subset of Ecommerce APIs"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /login:
    post:
      tags:
      - "login"
      summary: "Login to the application"
      description: "User must add Username and password to authenticate"
      operationId: "loginUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Login parameters"
        required: true
        schema:
          $ref: "#/definitions/login"
      responses:
        "200":
          description: "Successful Login"
        "401":
          $ref: '#/responses/UnauthenticatedError'
        "404":
          $ref: '#/responses/NotFoundError'
        "405":
          $ref: '#/responses/MethodNotAllowed'
        "503":
          $ref: '#/responses/InternalServerError'
      security:
      - basicAuth: []
  /register:
    post:
      tags:
      - "register"
      summary: "Create user"
      description: "This end point is to register a user"
      operationId: "registerUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/Register"
      responses:
        "201":
          description: "User created successfully"        
        "400":
          description: "Bad request"
        "405":
          $ref: '#/responses/MethodNotAllowed'
        "503":
          $ref: '#/responses/InternalServerError'
  /users:
    get:
      tags:
      - "users"
      summary: "Get the details of the users registered in the system"
      description: "This can be done only by an authenticated user"
      operationId: "user"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/users"
        "401":
          $ref: '#/responses/UnauthenticatedError'
        "403":
          $ref: '#/responses/UnauthorizedError'
        "503":
          $ref: '#/responses/InternalServerError'
      security:
        - basicAuth: []  
  /orders:
    get:
      tags:
      - "orders"
      summary: "Get the order details"
      description: "This can be done only by an authenticated user"
      operationId: "orders"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/order"
        "401":
          $ref: '#/responses/UnauthenticatedError'
        "403":
          $ref: '#/responses/UnauthorizedError'
        "503":
          $ref: '#/responses/InternalServerError'
      security:
        - basicAuth: []
  /wishlist:
    post:
      tags:
      - "wishlist"
      summary: "Create a wishlist"
      description: "This can be done only by an authenticated user"
      operationId: "wishlist"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Wishlist items"
        required: true
        schema:
          $ref: "#/definitions/wishlist"
      responses:
        "201":
          description: "Item successfully added"
        "401":
          $ref: '#/responses/UnauthenticatedError'
        "403":
          $ref: '#/responses/UnauthorizedError'
        "405":
          $ref: '#/responses/MethodNotAllowed'
        "503":
          $ref: '#/responses/InternalServerError'
      security:
      - basicAuth: []
securityDefinitions:
  basicAuth:
      type: basic
definitions:  
  login:
    type: "object"
    properties:
      username:
        type: "string"
        description: "username - the email used to register"
      password:
        type: "string"
        description: "Password set during registration"
  Register:
    type: "object"
    properties:
      firstName:
        type: "string"
        description: "First name"
      lastName:
        type: "string"
        description: "Last name"
      email:
        type: "string"
        description: "Valid email address"
      DOB:
        type: "string"
        description: "DOB should be in MM/DD/YYYY format"
      phone:
        type: "string"
        description: "Mobile number should be a 10 digit integer"
  users:
    type: "object"
    properties:
      firstName:
        type: "string"
        description: "User's First name"
      lastName:
        type: "string"
        description: "User's Last name"
      email:
        type: "string"
        description: "User's email address"
      DOB:
        type: "string"
        description: "Date of Birth"  
      phone:
        type: "string"
        description: "User's Contact number"
  order:
    type: "object"
    properties:
      itemid:
        type: "integer"
        format: "int64"
      itemname:
        type: "string"
      quantity:
        type: "string"
  wishlist:
    type: "object"
    properties:
      itemname:
        type: "string"
        description: "Can be any item like shoes etc"
responses:
  MethodNotAllowed:
    description: HTTP method is incorrect
  UnauthorizedError:
    description: User is not authorised for this page
  UnauthenticatedError:
    description: Authentication information is missing or invalid
  InternalServerError:
    description: Service not available
  NotFoundError:
    description: User Not found
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"          